import torch
import torch.nn.quantized.dynamic as nnqd


class LinearReLU(nnqd.Linear):
    def __init__(self, in_features, out_features, bias: bool = ..., dtype=...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    @classmethod
    def from_float(cls, mod): ...
    @classmethod
    def from_reference(cls, ref_qlinear_relu): ...
