from collections.abc import Generator

from _typeshed import Incomplete


class _NVTXStub:
    rangePushA: Incomplete
    rangePop: Incomplete
    markA: Incomplete

def range_push(msg): ...
def range_pop(): ...
def range_start(msg) -> int: ...
def range_end(range_id) -> None: ...
def mark(msg): ...
def range(msg, *args, **kwargs) -> Generator[None, None, None]: ...
