from typing import Iterable, List, Union

import torch

from .. import Tensor


def get_rng_state(device: Union[int, str, torch.device] = ...) -> Tensor: ...
def get_rng_state_all() -> List[Tensor]: ...
def set_rng_state(new_state: Tensor, device: Union[int, str, torch.device] = ...) -> None: ...
def set_rng_state_all(new_states: Iterable[Tensor]) -> None: ...
def manual_seed(seed: int) -> None: ...
def manual_seed_all(seed: int) -> None: ...
def seed() -> None: ...
def seed_all() -> None: ...
def initial_seed() -> int: ...
