from .utils import typename as typename


class VariadicSignatureType(type):
    def __subclasscheck__(cls, subclass): ...
    def __eq__(cls, other): ...
    def __hash__(cls): ...

def isvariadic(obj): ...

class VariadicSignatureMeta(type):
    def __getitem__(cls, variadic_type): ...

class Variadic: ...
