from typing import List


def get_all(store, rank: int, prefix: str, size: int): ...
def synchronize(store, data: bytes, rank: int, world_size: int, key_prefix: str, barrier_timeout: float = ...) -> List[bytes]: ...
def barrier(store, rank: int, world_size: int, key_prefix: str, barrier_timeout: float = ...) -> None: ...
