import torch.nn.quantized as nnq


class Linear(nnq.Linear):
    version: int
    def __init__(self, in_features, out_features, bias_: bool = ..., dtype=...) -> None: ...
    def forward(self, x): ...
    def extra_repr(self): ...
    @classmethod
    def from_float(cls, mod): ...
    @classmethod
    def from_reference(cls, ref_qlinear): ...
