from torch import nn as nn


def module_to_fqn(model, layer, prefix: str = ...): ...
def fqn_to_module(model, path): ...

class FakeSparsity(nn.Module):
    def __init__(self, mask) -> None: ...
    def forward(self, x): ...
    def state_dict(self, *args, **kwargs): ...
