from _typeshed import Incomplete


class _RequiredParameter: ...

required: Incomplete

class Optimizer:
    defaults: Incomplete
    state: Incomplete
    param_groups: Incomplete
    def __init__(self, params, defaults) -> None: ...
    def state_dict(self): ...
    def load_state_dict(self, state_dict): ...
    def zero_grad(self, set_to_none: bool = ...): ...
    def step(self, closure) -> None: ...
    def add_param_group(self, param_group) -> None: ...
