from _typeshed import Incomplete
from torch import Tensor as Tensor

from .module import Module as Module


class PixelShuffle(Module):
    __constants__: Incomplete
    upscale_factor: int
    def __init__(self, upscale_factor: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def extra_repr(self) -> str: ...

class PixelUnshuffle(Module):
    __constants__: Incomplete
    downscale_factor: int
    def __init__(self, downscale_factor: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def extra_repr(self) -> str: ...
