import multiprocessing.queues

from _typeshed import Incomplete


class ConnectionWrapper:
    conn: Incomplete
    def __init__(self, conn) -> None: ...
    def send(self, obj) -> None: ...
    def recv(self): ...
    def __getattr__(self, name): ...

class Queue(multiprocessing.queues.Queue):
    def __init__(self, *args, **kwargs) -> None: ...

class SimpleQueue(multiprocessing.queues.SimpleQueue): ...
