# pylint: disable=multiple-statements,unused-argument,invalid-name
# pylint: disable=too-few-public-methods,useless-import-alias,unused-import
# pylint: disable=redefined-builtin,super-init-not-called,arguments-renamed
# pylint: disable=abstract-method,too-many-ancestors,import-error
# pylint: disable=relative-beyond-top-level,redefined-outer-name
# pylint: disable=arguments-differ,no-member,keyword-arg-before-vararg
# pylint: disable=signature-differs,blacklisted-name,c-extension-no-member
# pylint: disable=protected-access,no-name-in-module,undefined-variable


from _typeshed import Incomplete
from torch import nn as nn


class OrderedDictWrapper:
    cpp_module: Incomplete
    attr: Incomplete
    def __init__(self, cpp_module, attr) -> None: ...
    @property
    def cpp_dict(self): ...
    def items(self): ...
    def keys(self): ...
    def values(self): ...
    def __iter__(self): ...
    def __len__(self): ...
    def __contains__(self, key): ...
    def __getitem__(self, key): ...


class ModuleWrapper(nn.Module):
    cpp_module: Incomplete
    def __init__(self, cpp_module) -> None: ...
    @property
    def training(self): ...
    @training.setter
    def training(self, mode) -> None: ...
