def conv1d_input(input_size, weight, grad_output, stride: int = ..., padding: int = ..., dilation: int = ..., groups: int = ...): ...
def conv1d_weight(input, weight_size, grad_output, stride: int = ..., padding: int = ..., dilation: int = ..., groups: int = ...): ...
def conv2d_input(input_size, weight, grad_output, stride: int = ..., padding: int = ..., dilation: int = ..., groups: int = ...): ...
def conv2d_weight(input, weight_size, grad_output, stride: int = ..., padding: int = ..., dilation: int = ..., groups: int = ...): ...
def conv3d_input(input_size, weight, grad_output, stride: int = ..., padding: int = ..., dilation: int = ..., groups: int = ...): ...
def conv3d_weight(input, weight_size, grad_output, stride: int = ..., padding: int = ..., dilation: int = ..., groups: int = ...): ...
