import torch
import torch.nn.quantized as nnq


class LinearReLU(nnq.Linear):
    def __init__(self, in_features, out_features, bias: bool = ..., dtype=...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    @classmethod
    def from_float(cls, mod): ...
    @classmethod
    def from_reference(cls, ref_linear_relu, output_scale, output_zero_point): ...
