from _typeshed import Incomplete


class EnabledProxy:
    enabled: Incomplete
    def __init__(self) -> None: ...
    def parse_env(self, name, default, true_message, false_message): ...
    def __bool__(self): ...

def disable() -> None: ...
def enable() -> None: ...
