from typing import Any

from _typeshed import Incomplete


class detect_anomaly:
    prev: Incomplete
    def __init__(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...

class set_detect_anomaly:
    prev: Incomplete
    def __init__(self, mode: bool) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...
