from _typeshed import Incomplete


def vjp(func, inputs, v: Incomplete | None = ..., create_graph: bool = ..., strict: bool = ...): ...
def jvp(func, inputs, v: Incomplete | None = ..., create_graph: bool = ..., strict: bool = ...): ...
def jacobian(func, inputs, create_graph: bool = ..., strict: bool = ..., vectorize: bool = ..., strategy: str = ...): ...
def hessian(func, inputs, create_graph: bool = ..., strict: bool = ..., vectorize: bool = ..., outer_jacobian_strategy: str = ...): ...
def vhp(func, inputs, v: Incomplete | None = ..., create_graph: bool = ..., strict: bool = ...): ...
def hvp(func, inputs, v: Incomplete | None = ..., create_graph: bool = ..., strict: bool = ...): ...
