import types

from _typeshed import Incomplete


class _ClassNamespace(types.ModuleType):
    name: Incomplete
    def __init__(self, name) -> None: ...
    def __getattr__(self, attr): ...

class _Classes(types.ModuleType):
    __file__: str
    def __init__(self) -> None: ...
    def __getattr__(self, name): ...
    @property
    def loaded_libraries(self): ...
    def load_library(self, path) -> None: ...

classes: Incomplete
