from _typeshed import Incomplete


class Library:
    m: Incomplete
    ns: Incomplete
    kind: Incomplete
    dispatch_key: Incomplete
    def __init__(self, ns, kind, dispatch_key: str = ...) -> None: ...
    def impl(self, op_name, fn, dispatch_key: str = ...) -> None: ...
    def define(self, schema, alias_analysis: str = ...): ...
    def __del__(self) -> None: ...

def impl(lib, name, dispatch_key: str = ...): ...
def define(lib, schema, alias_analysis: str = ...): ...
