from typing import Generator

import torch
from _typeshed import Incomplete
from torch._C import default_generator as default_generator


def set_rng_state(new_state: torch.Tensor) -> None: ...
def get_rng_state() -> torch.Tensor: ...
def manual_seed(seed) -> torch._C.Generator: ...
def seed() -> int: ...
def initial_seed() -> int: ...
def fork_rng(devices: Incomplete | None = ..., enabled: bool = ..., _caller: str = ..., _devices_kw: str = ...) -> Generator: ...
