from _typeshed import Incomplete


def merge(*dicts, **kwargs): ...
def merge_with(func, *dicts, **kwargs): ...
def valmap(func, d, factory=...): ...
def keymap(func, d, factory=...): ...
def itemmap(func, d, factory=...): ...
def valfilter(predicate, d, factory=...): ...
def keyfilter(predicate, d, factory=...): ...
def itemfilter(predicate, d, factory=...): ...
def assoc(d, key, value, factory=...): ...
def dissoc(d, *keys, **kwargs): ...
def assoc_in(d, keys, value, factory=...): ...
def update_in(d, keys, func, default: Incomplete | None = ..., factory=...): ...
def get_in(keys, coll, default: Incomplete | None = ..., no_default: bool = ...): ...
