from collections.abc import Generator

from .dispatch import dispatch as dispatch
from .utils import hashable as hashable


class Var:
    def __new__(cls, *token): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

def var(): ...
def vars(): ...
def isvar(v): ...
def variables(*variables) -> Generator[None, None, None]: ...
