from _typeshed import Incomplete
from torch.distributions import constraints as constraints
from torch.distributions.distribution import Distribution as Distribution
from torch.distributions.utils import lazy_property as lazy_property


class MultivariateNormal(Distribution):
    arg_constraints: Incomplete
    support: Incomplete
    has_rsample: bool
    loc: Incomplete
    def __init__(self, loc, covariance_matrix: Incomplete | None = ..., precision_matrix: Incomplete | None = ..., scale_tril: Incomplete | None = ..., validate_args: Incomplete | None = ...) -> None: ...
    def expand(self, batch_shape, _instance: Incomplete | None = ...): ...
    def scale_tril(self): ...
    def covariance_matrix(self): ...
    def precision_matrix(self): ...
    @property
    def mean(self): ...
    @property
    def mode(self): ...
    @property
    def variance(self): ...
    def rsample(self, sample_shape=...): ...
    def log_prob(self, value): ...
    def entropy(self): ...
