from _typeshed import Incomplete


class FileBaton:
    lock_file_path: Incomplete
    wait_seconds: Incomplete
    fd: Incomplete
    def __init__(self, lock_file_path, wait_seconds: float = ...) -> None: ...
    def try_acquire(self): ...
    def wait(self) -> None: ...
    def release(self) -> None: ...
