def fuse_conv_bn_eval(conv, bn, transpose: bool = ...): ...
def fuse_conv_bn_weights(conv_w, conv_b, bn_rm, bn_rv, bn_eps, bn_w, bn_b, transpose: bool = ...): ...
def fuse_linear_bn_eval(linear, bn): ...
def fuse_linear_bn_weights(linear_w, linear_b, bn_rm, bn_rv, bn_eps, bn_w, bn_b): ...
