from argparse import Action

from _typeshed import Incomplete


class env(Action):
    def __init__(self, dest, default: Incomplete | None = ..., required: bool = ..., **kwargs) -> None: ...
    def __call__(self, parser, namespace, values, option_string: Incomplete | None = ...) -> None: ...

class check_env(Action):
    def __init__(self, dest, default: bool = ..., **kwargs) -> None: ...
    def __call__(self, parser, namespace, values, option_string: Incomplete | None = ...) -> None: ...
