from typing import Optional, Union

import torch


class _remote_device:
    def __init__(self, remote_device: Union[str, torch.device]) -> None: ...
    def worker_name(self) -> Optional[str]: ...
    def rank(self) -> Optional[int]: ...
    def device(self) -> torch.device: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
