from _typeshed import Incomplete
from torch.cuda import nccl as nccl


def broadcast(tensor, devices: Incomplete | None = ..., *, out: Incomplete | None = ...): ...
def broadcast_coalesced(tensors, devices, buffer_size: int = ...): ...
def reduce_add(inputs, destination: Incomplete | None = ...): ...
def reduce_add_coalesced(inputs, destination: Incomplete | None = ..., buffer_size: int = ...): ...
def scatter(tensor, devices: Incomplete | None = ..., chunk_sizes: Incomplete | None = ..., dim: int = ..., streams: Incomplete | None = ..., *, out: Incomplete | None = ...): ...
def gather(tensors, dim: int = ..., destination: Incomplete | None = ..., *, out: Incomplete | None = ...): ...
