from ._functions import Gather as Gather
from ._functions import Scatter as Scatter


def is_namedtuple(obj): ...
def scatter(inputs, target_gpus, dim: int = ...): ...
def scatter_kwargs(inputs, kwargs, target_gpus, dim: int = ...): ...
def gather(outputs, target_device, dim: int = ...): ...
