from threading import Event
from typing import Dict, TextIO

from _typeshed import Incomplete


log: Incomplete

def tail_logfile(header: str, file: str, dst: TextIO, finished: Event, interval_sec: float): ...

class TailLog:
    def __init__(self, name: str, log_files: Dict[int, str], dst: TextIO, interval_sec: float = ...) -> None: ...
    def start(self) -> TailLog: ...
    def stop(self) -> None: ...
    def stopped(self) -> bool: ...
